### ISSUE TITLE
Rebooting but no jailbreak 

### ISSUE THREAD

**Issue by Exaucelunama** [iarchiveml/ra1ncloud#20]
It keeps automatically rebooting 30 secs after jailbreaking but when it comes back on , there is not a jailbreak anymore . Also the WiFI bug is still there on iPhone 11 iOS 15.3.1

**Comment by iarchiveml** [comment]
turn off wifi

**Comment by Exaucelunama** [comment]
> turn off wifi

I did . It wouldn't even jailbreak without turning the wifi off . My problem was that it jailbroke but the jailbreak didn't stay for long . I killed the Idownload and now it has stayed on for more than 5 minutes.
