### ISSUE TITLE
Crash after jailbreak fixed and wifi turned on with ios 15.2 on 13 pro max!!!!!

### ISSUE THREAD

**Issue by FkinPotatoe** [iarchiveml/ra1ncloud#22]
The newest release of ra1n cloud no longer crashes about 2 minutes after jailbreaking! 

+ I'm using wifi and I'm not getting the kernel panic!!

Thank you dev!

(It doesn't say you mentioned fixing these issues in the latest release though so I'm not sure if it's my lucky day or something but it works so who cares thanks ur the best!!)

**Comment by quaxxido** [comment]
11 iphone 15.2 still same kernel panic lol

**Comment by FkinPotatoe** [comment]
> 11 iphone 15.2 still same kernel panic lol

Hmm maybe reboot the device yourself and retry, and you downloaded the new ipa that was released 7 hrs ago with trollstore?
Like I said maybe it's my lucky day or something, I have the wifi on and it doesn't crash anymore. There's no tweak support though atm, I think they're still looking into that so if you can't get the new ipa to work I wouldn't worry too much until tweak support is available. 

I'm just glad I can actually jailbreak my phone and it's on 15.2 13 pro max, this is the only jailbreak that supports newer devices I believe so this is awesome even without tweak support haha.

**Comment by quaxxido** [comment]
> > 11 iphone 15.2 still same kernel panic lol
> 
> Hmm maybe reboot the device yourself and retry, and you downloaded the new ipa that was released 7 hrs ago with trollstore? Like I said maybe it's my lucky day or something, I have the wifi on and it doesn't crash anymore. There's no tweak support though atm, I think they're still looking into that so if you can't get the new ipa to work I wouldn't worry too much until tweak support is available.
> 
> I'm just glad I can actually jailbreak my phone and it's on 15.2 13 pro max, this is the only jailbreak that supports newer devices I believe so this is awesome even without tweak support haha.

I think i got it worked before this 0.3.3 version, but now nothing lol, i even tried uninstall, kill idownload and reboot device. sometimes it even crashes without wifi

**Comment by FkinPotatoe** [comment]
> I think i got it worked before this 0.3.3 version, but now nothing lol, i even tried uninstall, kill idownload and reboot device. sometimes it even crashes without wifi

Try installing it through trollstore, not sure what idownload. Lmk if that solves it

**Comment by quaxxido** [comment]
> > I think i got it worked before this 0.3.3 version, but now nothing lol, i even tried uninstall, kill idownload and reboot device. sometimes it even crashes without wifi
> 
> Try installing it through trollstore, not sure what idownload is. Lmk if that solves it

actually i have it installed thru trollstore

**Comment by FkinPotatoe** [comment]
> actually i have it installed thru trollstore

Hmm not sure then, if you had success with the old version use that for now but regardless the jailbreak doesn't allow you to install tweaks right now, not even filza so you could just wait until tweak support is implemented :)

**Comment by quaxxido** [comment]
> > actually i have it installed thru trollstore
> 
> Hmm not sure then, if you had success with the old version use that for now but regardless the jailbreak doesn't allow you to install tweaks right now, not even filza so you could just wait until tweak support is implemented :)

i wonder whats the meaning of jb without an tweak support? just for developing something? lol

**Comment by FkinPotatoe** [comment]
> i wonder whats the meaning of jb without an tweak support? just for developing something? lol

Yea, pretty much just developing I guess, but this jailbreak does have meaning lol there's no jailbreaks other than this one that supports newer devices like chips higher than a12 and iphone 13 pro max on firmware 15.2+, I'm surprised no one is really talking about this jailbreak because it's what people have been waiting for.. for so long the only thing that needs done now (I think) is just regular bug fixes and tweak support then this is a fully functional jailbreak : )

I think this jailbreak is still in the shadows a bit meaning not many people know about it just yet, but when they figure out this jailbreak exists the dev will be loved forever lmao

**Comment by quaxxido** [comment]
> > i wonder whats the meaning of jb without an tweak support? just for developing something? lol
> 
> Yea, pretty much just developing I guess, but this jailbreak does have meaning lol there's no jailbreaks other than this one that supports newer devices like chips higher than a12 and iphone 13 pro max on firmware 15.2+, I'm surprised no one is really talking about this jailbreak because it's what people have been waiting for.. for so long the only thing that needs done now (I think) is just regular bug fixes and tweak support then this is a fully functional jailbreak : )
> 
> I think this jailbreak is still in the shadows a bit meaning not many people know about it just yet, but when they figure out this jailbreak exists the dev will be loved forever lmao

yeah fr i am so surprised that no one knows about it, maybe its bcz of these strange kernel bugs that happens with fugu15 lol

**Comment by iarchiveml** [comment]
you really couldn't have done this in the discussions page?
