### ISSUE TITLE
zsh: killed     ipatool

### ISSUE THREAD

**Issue by chelaxian** [iarchiveml/ra1ncloud#27]
how can we use installed tweaks and debs from your default repos in ra1ncloud?
well, they successfully installed, but when trying to start it's binary command in terminal it gives "zsh: killed     XXX" error what ever package was used. 

I tried to fakesign this binary with "ldid -S $(which ipatool)" and try it for each package but it didn't help.

ok, tweak injection will not be supported in ra1ncloud, but what purpose of that jailbreak release if we even can't run binaries and can't use command line tools installed from repos?

**Comment by quaxxido** [comment]
it will be supported (not a 100% chance)

**Comment by iarchiveml** [comment]
you're supposed to press regenerate trustcache in the app after installing stuff.

**Comment by chelaxian** [comment]
This not helped, same problem after press button regenerate trustcache

**Comment by iarchiveml** [comment]
Pretty sure that package is broken then. I have no issues with this.

**Comment by iarchiveml** [comment]
ipatool works perfectly for me.

**Comment by chelaxian** [comment]
Ok after updating to 0.3.3 from 0.3.1 it works
